server:
  port: 5557

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgredb-1.cxpcrenyzzbl.us-east-2.rds.amazonaws.com:5432/jtraining?user=invauser&password=teVdInyxKGdJhRfOMip1&sslmode=require
  jpa:
    show-sql: true
    generate-ddl: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
